// GLP SOP 데이터 모델 및 시드 데이터
// GLP 규정 준수: 버전 관리, 상태 추적, Audit Trail 지원

export type SOPStatus = "effective" | "superseded" | "retired";

export interface SOPDocument {
  id: string;           // 고유 식별자 (예: IAI-GMS-001-02)
  number: string;       // SOP 번호 (예: IAI-GMS-001)
  version: string;      // 버전 (예: Rev.02)
  revision: number;     // 개정 번호 (정렬용)
  title: string;        // SOP 제목
  category: string;     // 카테고리 코드 (GMS, QAU 등)
  categoryName: string; // 카테고리 한글명
  effectiveDate: string;// 효력발생일
  createdDate: string;  // 제정일
  revisedDate: string;  // 최근 개정일
  author: string;       // 작성자
  reviewer: string;     // 검토자
  approver: string;     // 승인자
  status: SOPStatus;    // 현재 상태
  pdfPath: string;      // PDF 파일 경로 (서버에서 제공)
  keywords: string[];   // 검색 키워드
  description: string;  // 요약 설명
}

export interface AuditLog {
  id: string;
  sopId: string;
  userId: string;
  userName: string;
  action: "view" | "download" | "search";
  timestamp: string;    // ISO 8601
  ipAddress?: string;
  deviceInfo?: string;
}

export const CATEGORIES: Record<string, { name: string; description: string; color: string }> = {
  GMS: { name: "일반관리", description: "General Management System", color: "blue" },
  QAU: { name: "신뢰성보증", description: "Quality Assurance Unit", color: "purple" },
  TIP: { name: "시험물질", description: "Test Item Preparation", color: "green" },
  TIA: { name: "시험물질분석", description: "Test Item Analysis", color: "cyan" },
  ECT: { name: "생태독성시험", description: "Ecotoxicity Tests", color: "teal" },
  ANC: { name: "시험생물관리", description: "Animal/Organism Care", color: "orange" },
  TSF: { name: "시험시설", description: "Test Site Facilities", color: "red" },
  EQM: { name: "장비관리", description: "Equipment Management", color: "gray" },
};

// SOP 시드 데이터 (실제 파일 기반)
export const SOP_DATA: SOPDocument[] = [
  // GMS - 일반관리
  { id: "IAI-GMS-001-02", number: "IAI-GMS-001", version: "Rev.02", revision: 2, title: "표준작업지침서의 작성방법", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-04-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-001-02", keywords: ["작성", "SOP", "지침서", "방법"], description: "표준작업지침서(SOP)의 작성 형식, 절차 및 방법을 규정" },
  { id: "IAI-GMS-002-03", number: "IAI-GMS-002", version: "Rev.03", revision: 3, title: "표준작업지침서 관리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-04-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-002-03", keywords: ["관리", "SOP", "개정", "배포"], description: "SOP의 승인, 배포, 보관 및 개정 절차를 규정" },
  { id: "IAI-GMS-003-02", number: "IAI-GMS-003", version: "Rev.02", revision: 2, title: "GLP 시험기관 구성 및 업무", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-003-02", keywords: ["GLP", "조직", "구성", "업무"], description: "GLP 시험기관의 조직 구성 및 각 부서별 업무를 규정" },
  { id: "IAI-GMS-004-04", number: "IAI-GMS-004", version: "Rev.04", revision: 4, title: "교육 및 훈련", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-03-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-004-04", keywords: ["교육", "훈련", "연구원", "역량"], description: "연구원의 GLP 교육 및 훈련 계획, 실시 및 기록 방법을 규정" },
  { id: "IAI-GMS-005-01", number: "IAI-GMS-005", version: "Rev.01", revision: 1, title: "서명 등록 및 개인이력서 작성과 관리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2024-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-005-01", keywords: ["서명", "이력서", "등록", "개인"], description: "연구원 서명 등록 및 개인이력서 작성과 관리 절차를 규정" },
  { id: "IAI-GMS-006-05", number: "IAI-GMS-006", version: "Rev.05", revision: 5, title: "시험의 접수 및 실시", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-04-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-006-05", keywords: ["시험", "접수", "실시", "계약"], description: "시험 의뢰 접수부터 시험 실시까지의 절차를 규정" },
  { id: "IAI-GMS-007-01", number: "IAI-GMS-007", version: "Rev.01", revision: 1, title: "시험계획서 작성 및 관리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-007-01", keywords: ["시험계획서", "작성", "관리", "승인"], description: "시험계획서의 작성, 검토, 승인 및 관리 절차를 규정" },
  { id: "IAI-GMS-008-03", number: "IAI-GMS-008", version: "Rev.03", revision: 3, title: "문서의 작성 및 관리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-06-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-008-03", keywords: ["문서", "작성", "관리", "보관"], description: "시험 관련 문서의 작성, 수정, 보관 및 폐기 절차를 규정" },
  { id: "IAI-GMS-009-01", number: "IAI-GMS-009", version: "Rev.01", revision: 1, title: "시험기초자료의 통계처리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-06-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-009-01", keywords: ["통계", "데이터", "분석", "처리"], description: "시험기초자료의 통계적 처리 방법 및 절차를 규정" },
  { id: "IAI-GMS-010-00", number: "IAI-GMS-010", version: "Rev.00", revision: 0, title: "최종보고서 작성", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-010-00", keywords: ["최종보고서", "작성", "형식", "제출"], description: "시험 완료 후 최종보고서 작성 형식 및 절차를 규정" },
  { id: "IAI-GMS-011-00", number: "IAI-GMS-011", version: "Rev.00", revision: 0, title: "컴퓨터 시스템에 대한 검증", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-011-00", keywords: ["컴퓨터", "시스템", "검증", "CSV", "밸리데이션"], description: "GLP 시험에 사용되는 컴퓨터 시스템 밸리데이션(CSV) 절차를 규정" },
  { id: "IAI-GMS-012-01", number: "IAI-GMS-012", version: "Rev.01", revision: 1, title: "컴퓨터에서 생산된 자료의 관리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2024-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-012-01", keywords: ["컴퓨터", "전자데이터", "관리", "백업"], description: "컴퓨터 시스템에서 생산된 전자 데이터의 관리 절차를 규정" },
  { id: "IAI-GMS-013-02", number: "IAI-GMS-013", version: "Rev.02", revision: 2, title: "자료의 보관 및 자료보관실 관리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-013-02", keywords: ["자료", "보관", "아카이브", "보관실"], description: "시험 자료의 보관 방법 및 자료보관실 관리 절차를 규정" },
  { id: "IAI-GMS-014-00", number: "IAI-GMS-014", version: "Rev.00", revision: 0, title: "규제당국의 실태조사 대응절차", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-014-00", keywords: ["실태조사", "규제", "감사", "대응"], description: "규제 당국의 GLP 실태조사 시 대응 절차를 규정" },
  { id: "IAI-GMS-015-03", number: "IAI-GMS-015", version: "Rev.03", revision: 3, title: "시험시설의 운영 및 관리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-12-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-015-03", keywords: ["시험시설", "운영", "관리", "환경"], description: "시험시설의 전반적인 운영 및 관리 절차를 규정" },
  { id: "IAI-GMS-016-02", number: "IAI-GMS-016", version: "Rev.02", revision: 2, title: "폐기물 등의 관리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-016-02", keywords: ["폐기물", "처리", "환경", "안전"], description: "시험에서 발생하는 폐기물의 분리수거 및 처리 절차를 규정" },
  { id: "IAI-GMS-017-02", number: "IAI-GMS-017", version: "Rev.02", revision: 2, title: "시험실의 청소 및 기구세척", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-017-02", keywords: ["청소", "세척", "기구", "위생"], description: "시험실 청소 및 실험 기구의 세척 절차를 규정" },
  { id: "IAI-GMS-018-02", number: "IAI-GMS-018", version: "Rev.02", revision: 2, title: "물질관리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-018-02", keywords: ["물질", "시약", "관리", "보관"], description: "시험에 사용되는 시약 및 물질의 관리 절차를 규정" },
  { id: "IAI-GMS-019-04", number: "IAI-GMS-019", version: "Rev.04", revision: 4, title: "기기의 관리", category: "GMS", categoryName: "일반관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-03-01", author: "관리자", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-GMS-019-04", keywords: ["기기", "장비", "교정", "유지보수"], description: "시험에 사용되는 기기 및 장비의 관리, 교정 절차를 규정" },

  // QAU - 신뢰성보증
  { id: "IAI-QAU-001-00", number: "IAI-QAU-001", version: "Rev.00", revision: 0, title: "신뢰성보증팀의 책무", category: "QAU", categoryName: "신뢰성보증", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "QAU", reviewer: "기관장", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-QAU-001-00", keywords: ["QAU", "신뢰성", "책무", "역할"], description: "신뢰성보증팀(QAU)의 역할 및 책무를 규정" },
  { id: "IAI-QAU-002-01", number: "IAI-QAU-002", version: "Rev.01", revision: 1, title: "시험위주의 점검", category: "QAU", categoryName: "신뢰성보증", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2024-01-01", author: "QAU", reviewer: "기관장", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-QAU-002-01", keywords: ["점검", "QA", "시험", "감사"], description: "시험 진행 단계별 QAU 점검 절차를 규정" },
  { id: "IAI-QAU-003-00", number: "IAI-QAU-003", version: "Rev.00", revision: 0, title: "시설위주의 점검", category: "QAU", categoryName: "신뢰성보증", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "QAU", reviewer: "기관장", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-QAU-003-00", keywords: ["점검", "시설", "감사", "인프라"], description: "시험시설 및 기반시설에 대한 QAU 점검 절차를 규정" },
  { id: "IAI-QAU-004-02", number: "IAI-QAU-004", version: "Rev.02", revision: 2, title: "수행절차의 점검", category: "QAU", categoryName: "신뢰성보증", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "QAU", reviewer: "기관장", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-QAU-004-02", keywords: ["절차", "점검", "SOP", "준수"], description: "연구원의 SOP 준수 여부에 대한 QAU 점검 절차를 규정" },

  // TIP - 시험물질
  { id: "IAI-TIP-001-02", number: "IAI-TIP-001", version: "Rev.02", revision: 2, title: "시험물질 보관구역 및 조제구역 관리", category: "TIP", categoryName: "시험물질", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "연구원", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIP-001-02", keywords: ["시험물질", "보관", "조제구역", "관리"], description: "시험물질 보관 및 조제 구역의 관리 절차를 규정" },
  { id: "IAI-TIP-002-06", number: "IAI-TIP-002", version: "Rev.06", revision: 6, title: "시험물질의 수령 및 관리", category: "TIP", categoryName: "시험물질", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-04-01", author: "연구원", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIP-002-06", keywords: ["시험물질", "수령", "관리", "라벨"], description: "시험물질 수령 시 확인 사항 및 관리 절차를 규정" },
  { id: "IAI-TIP-003-04", number: "IAI-TIP-003", version: "Rev.04", revision: 4, title: "시험물질의 조제", category: "TIP", categoryName: "시험물질", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-02-01", author: "연구원", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIP-003-04", keywords: ["시험물질", "조제", "제조", "희석"], description: "시험에 사용할 시험물질 조제 절차를 규정" },
  { id: "IAI-TIP-004-00", number: "IAI-TIP-004", version: "Rev.00", revision: 0, title: "시험물질 오염예방에 관한 지침", category: "TIP", categoryName: "시험물질", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "연구원", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIP-004-00", keywords: ["오염", "예방", "교차오염", "시험물질"], description: "시험물질의 오염 예방을 위한 지침을 규정" },
  { id: "IAI-TIP-005-02", number: "IAI-TIP-005", version: "Rev.02", revision: 2, title: "용해도 및 안정성시험", category: "TIP", categoryName: "시험물질", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "연구원", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIP-005-02", keywords: ["용해도", "안정성", "시험물질", "분석"], description: "시험물질의 용해도 및 안정성 시험 절차를 규정" },

  // TIA - 시험물질분석
  { id: "IAI-TIA-001-02", number: "IAI-TIA-001", version: "Rev.02", revision: 2, title: "독성시험의 분석절차", category: "TIA", categoryName: "시험물질분석", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "분석팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIA-001-02", keywords: ["독성시험", "분석", "절차", "방법"], description: "독성시험에 사용되는 시험물질 분석 절차를 규정" },
  { id: "IAI-TIA-002-03", number: "IAI-TIA-002", version: "Rev.03", revision: 3, title: "분석방법 검증", category: "TIA", categoryName: "시험물질분석", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-06-01", author: "분석팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIA-002-03", keywords: ["분석방법", "검증", "validation", "정확도"], description: "분석 방법의 검증(Validation) 절차 및 판정 기준을 규정" },
  { id: "IAI-TIA-003-03", number: "IAI-TIA-003", version: "Rev.03", revision: 3, title: "시험용액의 분석", category: "TIA", categoryName: "시험물질분석", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-06-01", author: "분석팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIA-003-03", keywords: ["시험용액", "분석", "농도", "확인"], description: "시험에 사용되는 시험용액의 실제 농도 분석 절차를 규정" },
  { id: "IAI-TIA-004-00", number: "IAI-TIA-004", version: "Rev.00", revision: 0, title: "분석보고서 작성", category: "TIA", categoryName: "시험물질분석", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "분석팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIA-004-00", keywords: ["분석보고서", "작성", "형식"], description: "분석 결과에 대한 보고서 작성 절차를 규정" },
  { id: "IAI-TIA-005-00", number: "IAI-TIA-005", version: "Rev.00", revision: 0, title: "기기분석실 관리", category: "TIA", categoryName: "시험물질분석", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "분석팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIA-005-00", keywords: ["분석실", "기기", "관리", "환경"], description: "기기분석실의 환경 조건 및 관리 절차를 규정" },
  { id: "IAI-TIA-006-00", number: "IAI-TIA-006", version: "Rev.00", revision: 0, title: "용기진탕법을 이용한 분배계수시험", category: "TIA", categoryName: "시험물질분석", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "분석팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TIA-006-00", keywords: ["분배계수", "용기진탕", "LogP", "분석"], description: "용기진탕법을 이용한 분배계수(LogP) 시험 절차를 규정" },

  // ECT - 생태독성시험
  { id: "IAI-ECT-001-05", number: "IAI-ECT-001", version: "Rev.05", revision: 5, title: "어류급성독성시험", category: "ECT", categoryName: "생태독성시험", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-03-01", author: "생태팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-ECT-001-05", keywords: ["어류", "급성독성", "LC50", "물고기"], description: "어류 급성독성시험(LC50) 수행 절차를 규정" },
  { id: "IAI-ECT-002-03", number: "IAI-ECT-002", version: "Rev.03", revision: 3, title: "물벼룩급성독성시험", category: "ECT", categoryName: "생태독성시험", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-06-01", author: "생태팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-ECT-002-03", keywords: ["물벼룩", "급성독성", "EC50", "Daphnia"], description: "물벼룩(Daphnia) 급성독성시험(EC50) 수행 절차를 규정" },
  { id: "IAI-ECT-003-03", number: "IAI-ECT-003", version: "Rev.03", revision: 3, title: "담수조류생장저해시험", category: "ECT", categoryName: "생태독성시험", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-06-01", author: "생태팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-ECT-003-03", keywords: ["조류", "생장저해", "ErC50", "algae"], description: "담수조류 생장저해시험(ErC50) 수행 절차를 규정" },

  // ANC - 시험생물관리
  { id: "IAI-ANC-001-04", number: "IAI-ANC-001", version: "Rev.04", revision: 4, title: "어류의 사육관리", category: "ANC", categoryName: "시험생물관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-02-01", author: "생물관리팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-ANC-001-04", keywords: ["어류", "사육", "관리", "순화"], description: "시험에 사용되는 어류의 사육 및 관리 절차를 규정" },
  { id: "IAI-ANC-002-01", number: "IAI-ANC-002", version: "Rev.01", revision: 1, title: "어류의 안락사", category: "ANC", categoryName: "시험생물관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "생물관리팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-ANC-002-01", keywords: ["어류", "안락사", "처리"], description: "시험 완료 후 어류 안락사 처리 절차를 규정" },
  { id: "IAI-ANC-003-03", number: "IAI-ANC-003", version: "Rev.03", revision: 3, title: "물벼룩의 사육관리", category: "ANC", categoryName: "시험생물관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-06-01", author: "생물관리팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-ANC-003-03", keywords: ["물벼룩", "사육", "배양", "Daphnia"], description: "시험에 사용되는 물벼룩(Daphnia) 사육 및 관리 절차를 규정" },
  { id: "IAI-ANC-004-02", number: "IAI-ANC-004", version: "Rev.02", revision: 2, title: "조류의 배양관리", category: "ANC", categoryName: "시험생물관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "생물관리팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-ANC-004-02", keywords: ["조류", "배양", "algae", "관리"], description: "시험에 사용되는 담수조류 배양 및 관리 절차를 규정" },
  { id: "IAI-ANC-005-01", number: "IAI-ANC-005", version: "Rev.01", revision: 1, title: "배지의 조제", category: "ANC", categoryName: "시험생물관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "생물관리팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-ANC-005-01", keywords: ["배지", "조제", "배양액", "영양"], description: "시험생물 배양에 사용되는 배지 조제 절차를 규정" },
  { id: "IAI-ANC-006-02", number: "IAI-ANC-006", version: "Rev.02", revision: 2, title: "사육실 및 실험실의 관리", category: "ANC", categoryName: "시험생물관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "생물관리팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-ANC-006-02", keywords: ["사육실", "실험실", "환경조건", "관리"], description: "사육실 및 실험실의 환경 조건 모니터링 및 관리 절차를 규정" },

  // TSF - 시험시설
  { id: "IAI-TSF-001-01", number: "IAI-TSF-001", version: "Rev.01", revision: 1, title: "환기장치", category: "TSF", categoryName: "시험시설", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "시설팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TSF-001-01", keywords: ["환기", "공조", "HVAC", "시설"], description: "시험시설 환기장치의 운용 및 관리 절차를 규정" },
  { id: "IAI-TSF-002-01", number: "IAI-TSF-002", version: "Rev.01", revision: 1, title: "냉난방시스템", category: "TSF", categoryName: "시험시설", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "시설팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TSF-002-01", keywords: ["냉난방", "온도조절", "항온", "시설"], description: "시험시설 냉난방 시스템의 운용 및 관리 절차를 규정" },
  { id: "IAI-TSF-003-02", number: "IAI-TSF-003", version: "Rev.02", revision: 2, title: "비상전원장치", category: "TSF", categoryName: "시험시설", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "시설팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-TSF-003-02", keywords: ["비상전원", "UPS", "발전기", "정전"], description: "비상전원장치(UPS, 발전기)의 관리 및 비상 시 대응 절차를 규정" },

  // EQM - 장비관리
  { id: "IAI-EQM-001-00", number: "IAI-EQM-001", version: "Rev.00", revision: 0, title: "표준온도계", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-001-00", keywords: ["온도계", "표준", "교정"], description: "표준온도계의 교정 및 관리 절차를 규정" },
  { id: "IAI-EQM-002-01", number: "IAI-EQM-002", version: "Rev.01", revision: 1, title: "탐침온도계", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-002-01", keywords: ["온도계", "탐침", "교정", "검교정"], description: "탐침온도계의 검교정 및 관리 절차를 규정" },
  { id: "IAI-EQM-003-00", number: "IAI-EQM-003", version: "Rev.00", revision: 0, title: "위상차현미경", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-003-00", keywords: ["현미경", "위상차", "관찰"], description: "위상차현미경의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-004-04", number: "IAI-EQM-004", version: "Rev.04", revision: 4, title: "전자저울", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-03-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-004-04", keywords: ["저울", "칭량", "교정", "정밀"], description: "전자저울의 일상점검, 교정 및 사용 절차를 규정" },
  { id: "IAI-EQM-005-00", number: "IAI-EQM-005", version: "Rev.00", revision: 0, title: "고압증기멸균기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-005-00", keywords: ["멸균기", "오토클레이브", "고압증기", "멸균"], description: "고압증기멸균기(Autoclave)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-006-00", number: "IAI-EQM-006", version: "Rev.00", revision: 0, title: "조도계", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-006-00", keywords: ["조도계", "조도", "광량", "교정"], description: "조도계의 교정 및 사육실 조도 측정 절차를 규정" },
  { id: "IAI-EQM-007-01", number: "IAI-EQM-007", version: "Rev.01", revision: 1, title: "질소탱크", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-007-01", keywords: ["질소", "액체질소", "탱크", "안전"], description: "액체질소 탱크의 취급, 보관 및 안전 관리 절차를 규정" },
  { id: "IAI-EQM-008-02", number: "IAI-EQM-008", version: "Rev.02", revision: 2, title: "클린벤치", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-008-02", keywords: ["클린벤치", "무균", "HEPA", "청정"], description: "클린벤치(Clean Bench)의 운용, 소독 및 관리 절차를 규정" },
  { id: "IAI-EQM-009-00", number: "IAI-EQM-009", version: "Rev.00", revision: 0, title: "pH DO미터", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-009-00", keywords: ["pH", "DO", "용존산소", "측정"], description: "pH/DO 복합 측정기의 교정 및 운용 절차를 규정" },
  { id: "IAI-EQM-010-01", number: "IAI-EQM-010", version: "Rev.01", revision: 1, title: "흄후드", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-010-01", keywords: ["흄후드", "유해가스", "환기", "안전"], description: "흄후드(Fume Hood)의 운용 및 안전 관리 절차를 규정" },
  { id: "IAI-EQM-011-01", number: "IAI-EQM-011", version: "Rev.01", revision: 1, title: "진탕배양기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-011-01", keywords: ["진탕배양기", "shaker", "배양", "교반"], description: "진탕배양기(Shaking Incubator)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-012-00", number: "IAI-EQM-012", version: "Rev.00", revision: 0, title: "초음파 분산기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-012-00", keywords: ["초음파", "분산기", "소니케이터", "분산"], description: "초음파 분산기(Sonicator)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-013-00", number: "IAI-EQM-013", version: "Rev.00", revision: 0, title: "원심분리기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-013-00", keywords: ["원심분리기", "원심분리", "분리"], description: "원심분리기(Centrifuge)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-014-01", number: "IAI-EQM-014", version: "Rev.01", revision: 1, title: "정수장치", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-014-01", keywords: ["정수장치", "정수", "수질", "관리"], description: "시험용수 생산을 위한 정수장치의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-015-01", number: "IAI-EQM-015", version: "Rev.01", revision: 1, title: "경도계", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-015-01", keywords: ["경도계", "수질경도", "측정"], description: "경도계의 교정 및 수질 경도 측정 절차를 규정" },
  { id: "IAI-EQM-016-00", number: "IAI-EQM-016", version: "Rev.00", revision: 0, title: "버니어캘리퍼스", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-016-00", keywords: ["캘리퍼스", "길이", "측정", "교정"], description: "버니어캘리퍼스의 교정 및 사용 절차를 규정" },
  { id: "IAI-EQM-017-02", number: "IAI-EQM-017", version: "Rev.02", revision: 2, title: "냉동냉장고", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-017-02", keywords: ["냉동냉장고", "보관", "온도", "시약"], description: "시약 및 시험물질 보관용 냉동냉장고의 관리 절차를 규정" },
  { id: "IAI-EQM-018-00", number: "IAI-EQM-018", version: "Rev.00", revision: 0, title: "초순수기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-018-00", keywords: ["초순수기", "초순수", "증류수", "수질"], description: "초순수기(Ultrapure Water System)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-019-04", number: "IAI-EQM-019", version: "Rev.04", revision: 4, title: "피펫", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2026-03-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-019-04", keywords: ["피펫", "교정", "부피", "정확도"], description: "마이크로피펫 및 피펫의 교정 및 관리 절차를 규정" },
  { id: "IAI-EQM-020-02", number: "IAI-EQM-020", version: "Rev.02", revision: 2, title: "배양기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-020-02", keywords: ["배양기", "인큐베이터", "온도", "배양"], description: "배양기(Incubator)의 운용, 온도 모니터링 및 관리 절차를 규정" },
  { id: "IAI-EQM-021-00", number: "IAI-EQM-021", version: "Rev.00", revision: 0, title: "TOC 측정계", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-021-00", keywords: ["TOC", "총유기탄소", "수질", "측정"], description: "TOC 측정계의 운용 및 수질 내 총유기탄소 측정 절차를 규정" },
  { id: "IAI-EQM-023-02", number: "IAI-EQM-023", version: "Rev.02", revision: 2, title: "온습도기록계", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-023-02", keywords: ["온습도", "기록계", "데이터로거", "모니터링"], description: "온습도기록계의 교정, 운용 및 데이터 관리 절차를 규정" },
  { id: "IAI-EQM-024-03", number: "IAI-EQM-024", version: "Rev.03", revision: 3, title: "온도 기록계", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-06-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-024-03", keywords: ["온도", "기록계", "데이터로거", "모니터링"], description: "온도기록계의 교정, 운용 및 데이터 관리 절차를 규정" },
  { id: "IAI-EQM-025-00", number: "IAI-EQM-025", version: "Rev.00", revision: 0, title: "잔류염소계", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-025-00", keywords: ["잔류염소", "염소", "수질", "측정"], description: "잔류염소계를 이용한 수질 내 잔류염소 측정 절차를 규정" },
  { id: "IAI-EQM-026-00", number: "IAI-EQM-026", version: "Rev.00", revision: 0, title: "드라이 오븐", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-026-00", keywords: ["오븐", "건조", "열처리", "멸균"], description: "드라이 오븐(Dry Oven)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-027-02", number: "IAI-EQM-027", version: "Rev.02", revision: 2, title: "유도결합플라즈마 광학방출분광기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-06-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-027-02", keywords: ["ICP", "OES", "금속분석", "분광기"], description: "ICP-OES 장비의 운용, 유지보수 및 관리 절차를 규정" },
  { id: "IAI-EQM-028-01", number: "IAI-EQM-028", version: "Rev.01", revision: 1, title: "액체크로마토그래피 질량분석기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2024-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-028-01", keywords: ["LC-MS", "크로마토그래피", "질량분석"], description: "LC-MS/MS 장비의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-029-01", number: "IAI-EQM-029", version: "Rev.01", revision: 1, title: "기체크로마토그래피 질량분석기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2024-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-029-01", keywords: ["GC-MS", "크로마토그래피", "휘발성"], description: "GC-MS 장비의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-030-01", number: "IAI-EQM-030", version: "Rev.01", revision: 1, title: "고성능 액체크로마토그래피", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2024-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-030-01", keywords: ["HPLC", "크로마토그래피", "분석"], description: "HPLC 장비의 운용, 교정 및 관리 절차를 규정" },
  { id: "IAI-EQM-031-01", number: "IAI-EQM-031", version: "Rev.01", revision: 1, title: "기체크로마토그래피 불꽃이온화검출기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2024-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-031-01", keywords: ["GC-FID", "크로마토그래피", "불꽃이온화"], description: "GC-FID 장비의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-032-01", number: "IAI-EQM-032", version: "Rev.01", revision: 1, title: "세포계수기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2024-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-032-01", keywords: ["세포계수기", "혈구계", "계수", "조류"], description: "세포계수기(Hemocytometer)를 이용한 조류 세포 계수 절차를 규정" },
  { id: "IAI-EQM-033-03", number: "IAI-EQM-033", version: "Rev.03", revision: 3, title: "외부여과기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2020-01-01", revisedDate: "2025-06-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-033-03", keywords: ["여과기", "필터", "수조", "수질"], description: "사육 수조용 외부여과기의 설치, 세척 및 관리 절차를 규정" },
  { id: "IAI-EQM-034-00", number: "IAI-EQM-034", version: "Rev.00", revision: 0, title: "냉각기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-034-00", keywords: ["냉각기", "칠러", "온도조절", "수조"], description: "사육 수조 수온 조절을 위한 냉각기(Chiller)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-035-00", number: "IAI-EQM-035", version: "Rev.00", revision: 0, title: "교반기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-035-00", keywords: ["교반기", "스터러", "혼합", "마그네틱"], description: "마그네틱 교반기(Stirrer)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-036-00", number: "IAI-EQM-036", version: "Rev.00", revision: 0, title: "볼텍스", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-036-00", keywords: ["볼텍스", "혼합", "vortex"], description: "볼텍스 믹서(Vortex Mixer)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-042-00", number: "IAI-EQM-042", version: "Rev.00", revision: 0, title: "pH미터", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-042-00", keywords: ["pH미터", "pH", "교정", "측정"], description: "pH미터의 교정 및 pH 측정 절차를 규정" },
  { id: "IAI-EQM-043-00", number: "IAI-EQM-043", version: "Rev.00", revision: 0, title: "풍속계", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-043-00", keywords: ["풍속계", "풍속", "환기", "측정"], description: "풍속계를 이용한 시험시설 환기량 측정 절차를 규정" },
  { id: "IAI-EQM-045-01", number: "IAI-EQM-045", version: "Rev.01", revision: 1, title: "TOC 분석기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2021-01-01", revisedDate: "2023-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-045-01", keywords: ["TOC", "총유기탄소", "분석기", "수질"], description: "TOC 분석기의 운용, 교정 및 관리 절차를 규정" },
  { id: "IAI-EQM-046-00", number: "IAI-EQM-046", version: "Rev.00", revision: 0, title: "회전감압농축기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-046-00", keywords: ["로타리에바포레이터", "농축기", "감압농축", "용매"], description: "회전감압농축기(Rotary Evaporator)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-047-00", number: "IAI-EQM-047", version: "Rev.00", revision: 0, title: "튜브 로테이터", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-047-00", keywords: ["튜브로테이터", "혼합", "회전"], description: "튜브 로테이터(Tube Rotator)의 운용 및 관리 절차를 규정" },
  { id: "IAI-EQM-048-00", number: "IAI-EQM-048", version: "Rev.00", revision: 0, title: "분액 여두 진탕기", category: "EQM", categoryName: "장비관리", effectiveDate: "2026-05-11", createdDate: "2022-01-01", revisedDate: "2022-01-01", author: "장비팀", reviewer: "QAU", approver: "기관장", status: "effective", pdfPath: "/api/sop/IAI-EQM-048-00", keywords: ["분액여두", "진탕기", "추출", "분배"], description: "분액 여두 진탕기를 이용한 용매 추출 절차를 규정" },
];

// SOP 검색 함수
export function searchSOPs(query: string): SOPDocument[] {
  if (!query.trim()) return SOP_DATA.filter(s => s.status === "effective");
  const q = query.toLowerCase();
  return SOP_DATA.filter(s =>
    s.status === "effective" && (
      s.title.toLowerCase().includes(q) ||
      s.number.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q) ||
      s.categoryName.includes(q) ||
      s.keywords.some(k => k.toLowerCase().includes(q)) ||
      s.description.toLowerCase().includes(q)
    )
  );
}

// 카테고리별 그룹화
export function groupByCategory(sops: SOPDocument[]): Record<string, SOPDocument[]> {
  return sops.reduce((acc, sop) => {
    if (!acc[sop.category]) acc[sop.category] = [];
    acc[sop.category].push(sop);
    return acc;
  }, {} as Record<string, SOPDocument[]>);
}
